-- Contas e autenticação: users e os três fluxos de token por e-mail (cadastro
-- pendente, redefinição de senha, troca de e-mail). Substitui users.json,
-- counters.json/__meta, pending-registrations.json, password-resets.json e
-- email-changes.json.
--
-- Os nomes de coluna espelham as chaves dos JSON em snake_case (profilePhoto →
-- profile_photo), para o mapeamento entre os dois ser direto.
--
-- O banco garante o que o código não consegue garantir sob concorrência:
-- unicidade, papéis válidos, vínculos. Formato de campo (regex de username,
-- tamanho do nome) segue validado no app, como já é.

CREATE TABLE users (
  -- IDENTITY nunca devolve um valor já usado, nem depois de um DELETE — é a
  -- regra que counters.json/__meta implementava à mão (CLAUDE.md §5.2). O pg
  -- devolve BIGINT como string, então `u.id === req.params.id` segue valendo.
  --
  -- BY DEFAULT, e não ALWAYS, para seed e testes poderem gravar ids explícitos.
  -- Quem fizer isso precisa avançar a sequência em seguida (setval), senão o
  -- próximo INSERT sem id colide com um id gravado à mão.
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username            TEXT NOT NULL,
  name                TEXT NOT NULL,
  role                TEXT NOT NULL
                        CHECK (role IN ('admin', 'supervisor', 'therapist', 'external', 'evaluator')),
  -- RESTRICT: excluir um professor com alunos vinculados é recusado, igual à
  -- tela de Contas. Não há NOT NULL para aluno interno: quando um professor
  -- muda de função, os alunos dele ficam sem vínculo (PUT /api/admin/users).
  teacher_id          BIGINT REFERENCES users (id) ON DELETE RESTRICT,
  password_hash       TEXT NOT NULL,
  token_version       INTEGER NOT NULL DEFAULT 0,
  -- NULL = conta sem e-mail, permitido em conta criada pelo admin. No JSON isso
  -- era a string vazia; aqui precisa ser NULL para o índice único aceitar
  -- várias contas sem endereço.
  email               TEXT,
  email_verified      BOOLEAN NOT NULL DEFAULT false,
  gender              TEXT NOT NULL DEFAULT '',
  profile_photo       TEXT NOT NULL DEFAULT '',
  visual_description  TEXT,
  -- Consentimento de mostrar a aparência aos pacientes simulados. NULL (nunca
  -- respondeu) é diferente de false (recusou), por isso não tem default.
  share_appearance    BOOLEAN,
  sidequests_enabled  BOOLEAN NOT NULL DEFAULT true,
  abordagem           TEXT NOT NULL DEFAULT '',
  active_title        TEXT NOT NULL DEFAULT '',
  update_all_os       BOOLEAN NOT NULL DEFAULT false,
  update_allos        BOOLEAN NOT NULL DEFAULT false,
  -- origem {canal, detalhe} e consentimento.termos {em, versao} viram colunas:
  -- são os campos que se consultam (de onde vêm os alunos; que versão dos
  -- termos cada um aceitou, que é o que a LGPD pede).
  origem_canal        TEXT,
  origem_detalhe      TEXT,
  termos_aceito_em    TIMESTAMPTZ,
  termos_versao       TEXT,
  criado_em           TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT users_teacher_so_para_aluno
    CHECK (teacher_id IS NULL OR role IN ('therapist', 'external'))
);

-- Unicidade sem distinguir maiúsculas (CLAUDE.md §5.3). Substitui os campos
-- usernameLower/emailLower, que existiam só porque JSON não tem índice.
CREATE UNIQUE INDEX users_username_lower_uq ON users (lower(username));
CREATE UNIQUE INDEX users_email_lower_uq ON users (lower(email)) WHERE email IS NOT NULL;
CREATE INDEX users_teacher_id_idx ON users (teacher_id) WHERE teacher_id IS NOT NULL;


-- Cadastro público aguardando o clique no link (48h). A conta só nasce na
-- confirmação. O token viaja no e-mail; aqui fica só o SHA-256.
CREATE TABLE pending_registrations (
  token_hash          TEXT PRIMARY KEY,
  expires_at          TIMESTAMPTZ NOT NULL,
  criado_em           TIMESTAMPTZ NOT NULL DEFAULT now(),
  username            TEXT NOT NULL,
  name                TEXT NOT NULL,
  email               TEXT NOT NULL,
  password_hash       TEXT NOT NULL,
  origem_canal        TEXT,
  origem_detalhe      TEXT,
  termos_aceito_em    TIMESTAMPTZ NOT NULL,
  termos_versao       TEXT NOT NULL,
  update_all_os       BOOLEAN NOT NULL DEFAULT false,
  update_allos        BOOLEAN NOT NULL DEFAULT false,
  ip                  TEXT,
  -- Vale assinado do duelo feito como visitante, transferido na confirmação.
  duel_claim          JSONB
);

-- Uma pendência "segura" o nome e o e-mail até vencer. São os índices que
-- impedem dois cadastros simultâneos de passarem juntos pela checagem. Como uma
-- pendência vencida continua segurando o nome até ser apagada, o código de
-- cadastro precisa remover as vencidas na mesma transação, antes de inserir.
CREATE UNIQUE INDEX pending_registrations_username_lower_uq ON pending_registrations (lower(username));
CREATE UNIQUE INDEX pending_registrations_email_lower_uq ON pending_registrations (lower(email));
CREATE INDEX pending_registrations_expires_at_idx ON pending_registrations (expires_at);


-- Pedido de nova senha (1h).
CREATE TABLE password_resets (
  token_hash  TEXT PRIMARY KEY,
  -- UNIQUE: um pedido por conta. Pedir de novo substitui o link anterior.
  user_id     BIGINT NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
  expires_at  TIMESTAMPTZ NOT NULL,
  criado_em   TIMESTAMPTZ NOT NULL DEFAULT now(),
  ip          TEXT
);
CREATE INDEX password_resets_expires_at_idx ON password_resets (expires_at);


-- Troca de e-mail aguardando confirmação no endereço novo (48h).
CREATE TABLE email_changes (
  token_hash  TEXT PRIMARY KEY,
  user_id     BIGINT NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
  email       TEXT NOT NULL,
  expires_at  TIMESTAMPTZ NOT NULL,
  criado_em   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX email_changes_expires_at_idx ON email_changes (expires_at);
