-- Processo Seletivo e Comunidade: substitui selection-logs.json,
-- selection-stats.json e comunidade.json. (A configuração da Comunidade —
-- banimentos e avatar institucional — vai para `configuracoes`, chave
-- 'comunidade-config'.)


-- PROCESSO SELETIVO — o atendimento completo do candidato, com a avaliação.
-- Retenção de 15 dias (CLAUDE.md §5.5). O documento é o log de sempre (dados do
-- candidato, mensagens, nota, feedback prévio); as chaves de busca viram colunas.
-- A transcrição mora no documento pelo mesmo motivo dos duelos: é enviada uma
-- vez, no fim, e sempre lida junto com o log.
CREATE TABLE selecao_logs (
  id            TEXT PRIMARY KEY,
  -- Uma sessão do candidato gera no máximo um log: o /finish repetido não duplica.
  session_id    TEXT NOT NULL UNIQUE,
  criado_em     TIMESTAMPTZ NOT NULL,
  -- WhatsApp só com dígitos: um atendimento por número a cada 15 dias.
  whatsapp      TEXT NOT NULL DEFAULT '',
  status        TEXT NOT NULL,
  eval_batch_id TEXT,
  doc           JSONB NOT NULL
);

CREATE INDEX selecao_logs_criado_em_idx ON selecao_logs (criado_em);
CREATE INDEX selecao_logs_whatsapp_idx ON selecao_logs (whatsapp, criado_em DESC);
CREATE INDEX selecao_logs_pendentes_idx ON selecao_logs (eval_batch_id) WHERE status = 'pending';

-- Estatísticas ANÔNIMAS e PERMANENTES da dashboard: sem PII, sem mensagens.
-- Sobrevivem à poda dos logs.
CREATE TABLE selecao_estatisticas (
  id        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  criado_em TIMESTAMPTZ NOT NULL,
  score     DOUBLE PRECISION,
  status    TEXT NOT NULL
);

CREATE INDEX selecao_estatisticas_criado_em_idx ON selecao_estatisticas (criado_em);


-- COMUNIDADE — uma discussão por linha, com os comentários, votos e enquete
-- dentro do documento (a tela lê e o módulo server/comunidade.js monta a
-- discussão inteira). Comentar ou votar trava só aquela discussão. O id é
-- sequencial porque vai na URL pública (/comunidade/discussao/1).
CREATE TABLE comunidade_discussoes (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Sem FK: o autor é gravado só com o papel, e a identidade vem da conta viva.
  author_id TEXT,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  doc       JSONB NOT NULL
);

CREATE INDEX comunidade_discussoes_autor_idx ON comunidade_discussoes (author_id);
